import React from "react";

function Main() {
  return (
        <main class="main">
            <section class="about">
                <h2 class="section-title">About</h2>
                <p class="section-para">Front-End or Back-End web development with proven Civil Engineering background will make a perfect start up with the century of this modern era of technologies.
I have recently earned a certificate in full-stack web development from Carleton University coding Bootcamp program. It was an amazing time that I have spent in the program, letting me to get lots of experiences and have developed skills in Front as well as Back-end web development with newly emerged technologies and web packages. To mention some, for front-end, JavaScript and React.js with deepen experiences in HTML and CSS with due care implementation of the mobile responsiveness principle were few of them. In the Back-end development, the vital Node.js and Express.js are something that I have well developed through the time of course with deployed projects. My Re-presentational state transferring application programming interface experience has also been accompanied by the most useful CRUD operated projects with manageable database establishment with SQL as well as NOSQL. In doing several projects, with each project, I have valued the essentiality of User interface enhancement, reliable server establishment and formation of well-structured database system for data addition, deletion, and update. My final project was a single page MERN application that I have done it with, group of three members that could potentially be able to assist local farmers and buyers to own a stall to sell their produce as well as buy directly as a customer from the application respectively. I am very encouraged to read and research more on modern web technologies and so excited to render my skills into the world to offer to the best of my knowledge as well as to get better experience in return in web application process.</p>
            </section>

            <section class="interest">
                <h2 class="section-title">Interest</h2>
                <p class="section-para">Front-End or Back-End web development with proven Civil Engineering background will make a perfect start up with the century of this modern era of technologies.
I have recently earned a certificate in full-stack web development from Carleton University coding Bootcamp program. It was an amazing time that I have spent in the program, letting me to get lots of experiences and have developed skills in Front as well as Back-end web development with newly emerged technologies and web packages. To mention some, for front-end, JavaScript and React.js with deepen experiences in HTML and CSS with due care implementation of the mobile responsiveness principle were few of them. In the Back-end development, the vital Node.js and Express.js are something that I have well developed through the time of course with deployed projects. My Re-presentational state transferring application programming interface experience has also been accompanied by the most useful CRUD operated projects with manageable database establishment with SQL as well as NOSQL. In doing several projects, with each project, I have valued the essentiality of User interface enhancement, reliable server establishment and formation of well-structured database system for data addition, deletion, and update. My final project was a single page MERN application that I have done it with, group of three members that could potentially be able to assist local farmers and buyers to own a stall to sell their produce as well as buy directly as a customer from the application respectively. I am very encouraged to read and research more on modern web technologies and so excited to render my skills into the world to offer to the best of my knowledge as well as to get better experience in return in web application process.</p>
            </section>
        </main>
  );
}

export default Main;